### ISSUE TITLE
使用datagrid操作列时需动态获取列坐标

### ISSUE THREAD

**Issue by hegja** [dcfs-pmo/dcfs-javascript-custom-rules#2]
规则简介：
使用datagrid数组时，进行具体列的取值和赋值时，存在写死列坐标的场景，如此编码对于后续的数组扩展和调整非常不利，应当通过列名动态获取列坐标，以此提高代码的扩展性。
规则描述：
错误的代码示例：
datagrid.cells(r,1)
正确的代码示例：
datagrid.cells(r,datagrid.getColIndexById("QUERY_BANK_CODE"))
即使用此方法时第二个参数不允许为数字
规则是否自己实现：否
规则提交人：hegja

**Comment by dcfspmo** [comment]
评估是否能实现中以及现有规则是否覆盖中
