### ISSUE TITLE
定时器函数的执行参数使用方法名字符串，其实会使用eval()执行函数

### ISSUE THREAD

**Issue by J-HECQ** [dcfs-pmo/dcfs-javascript-custom-rules#3]
规则简介：
定时器函数的执行参数使用方法名字符串，其实会使用eval()执行函数
规则描述：
定时器函数的执行参数使用方法名字符串，其实会使用eval()执行函数
错误的代码示例：
// Noncompliant  
setTimeout("myFunc()", 1000); 
setTimeout("myFunc(1, 2, 3)", 1000); 

setInterval("myFunc()", 1000); 
setInterval("myFunc(1, 2, 3)", 1000);
正确的代码示例：
// Ok
setTimeout(myFunc, 1000); 
setTimeout(function () { myFunc(1, 2, 3); }, 1000);

setInterval(myFunc, 1000); 
setInterval(function () { myFunc(1, 2, 3); }, 1000);
即使用setTimeout定时器时，第一个参数请直接传递function
规则是否自己实现：是
规则提交人：hecq

**Comment by dcfspmo** [comment]
捉虫级，已实现完毕
