### ISSUE TITLE
使用if或者箭头函数时，即使只有一行代码也要使用大括号 {},来定义代码块。

### ISSUE THREAD

**Issue by J-HECQ** [dcfs-pmo/dcfs-javascript-custom-rules#4]
规则简介：
使用if或者箭头函数时，即使只有一行代码也要使用大括号 {},来定义代码块。
规则描述：
使用if或者箭头函数时，即使只有一行代码也要使用大括号 {},来定义代码块。
错误的代码示例：
// Noncompliant  
if(condition)
  doSomeThing();
	
var func = () => doSmoeThing();

() => doSomeThing();

正确的代码示例：
// Ok
if(condition){
  doSomeThing();
}

var func = () => {doSmoeThing();}

() => {doSomeThing();}
即哪怕只有一行代码也需要书写{ }，来定义代码块，使得代码结构清晰并不会执行多余代码导致异常。
规则是否自己实现：是
规则提交人：hecq

**Comment by dcfspmo** [comment]
和已有规则：Control structures should use curly braces，Braces and parentheses should be used consistently with arrow functions有重复和冲突
