### ISSUE TITLE
如果表达式出  await 关键字，则父方法必须使用async修饰 ，否则运行时抛出异常

### ISSUE THREAD

**Issue by J-HECQ** [dcfs-pmo/dcfs-javascript-custom-rules#5]
规则简介：
如果表达式出  await 关键字，则父方法必须使用async修饰 ，否则运行时抛出异常。
规则描述：
如果表达式出  await 关键字，则父方法必须使用async修饰 ，否则运行时抛出异常。
错误的代码示例：
// Noncompliant 
function run1() {
	await waitFiles();
}

function run2(){
	waitFiles(function (){
		await doSomeThing();
	});
}

async function run3(){
	waitFiles(function (){
		await doSomeThing();
	});
}
正确的代码示例：
// Ok
// OK
async function run4() {
	await waitFiles();
}

function run5(){
	waitFiles(async function (){
		await doSomeThing();
	});
}
即使用await时，父 function 必须 定义为 async，否则运行抛出异常。
规则是否自己实现：是
规则提交人：hecq

**Comment by dcfspmo** [comment]
捉虫级，关闭
